name: Run unit tests

on:
  push:
    branches: [development, dev, check_branch, test/ci_cd]
  pull_request:
    branches: [development, dev, check_branch, test/ci_cd]

jobs:
  build:
    name: Build Angular Project
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: testing changes check
        run: |
          dir
          $env:path -split ';' | Select-String nodejs

      - name: Install dependencies
        run: node -v
         
         

      - name: Install Angular CLI
        run: |
           npm i -f
           npm install -g @angular/cli
           ng build 
           pwd
           dir
